#!/bin/sh
#
# $FreeBSD$
#

if [ $# -eq 0 ]; then
	out=`getent hosts`
	[ $? -eq 0 ] || exit 1
	echo "$out" | awk '{ print $2 }' | sort -u
	exit 0
fi

# Check to see if the remote system is running NFSv4
rpcinfo -T tcp "$1" nfs 2>/dev/null | grep -q "version 4"
if [ $? -eq 0 ] ; then
	# NFSv4 only needs one mount to access all exported filessytems
	echo "/ -nfsv4 $1:/"
else
	out=`showmount -E "$1"`
	[ $? -eq 0 ] || exit 1
	echo "$out" | awk -v host="$1" \
	    '{ printf "\"%s\"\t\"%s:%s\" ", $0, host, $0 } END { printf "\n" }'
fi
